# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix: 
        architecture : [x86,x64]
        dotnet: [4.5.1,4.8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --runtime ${{ matrix.architecture }} --configuration release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --runtime ${{ matrix.architecture }} --output ./artifacts
    - name: Upload ${{ matrix.architecture }} ${{matrix.dotnet}} Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.architecture }}-${{matrix.dotnet}} myProject
        path: ./artifacts
          
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        path: .
    - name: Package
      run: dotnet nuget push
          
