name: environment-demo

on:
  workflow_dispatch:
    inputs:
      environments:
        type: environment
        description: "which environment?"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🏗️ Build completed"

  qa:
    runs-on: ubuntu-latest
    needs: build
    environment: test
    steps:
      - run: echo ${{ vars.SERVICE_ACCOUNT_NAME }} ; echo ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
      - if: ${{ inputs.environments == 'qa' }}
        run: echo "🔍 Special steps for selected environment ${{ inputs.environments }}" >> $GITHUB_STEP_SUMMARY

  dev:
    runs-on: ubuntu-latest
    needs: build
    environment: qa
    steps:
      - run: echo ${{ vars.SERVICE_ACCOUNT_NAME }} ; echo ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
      - if: ${{ inputs.environments == 'dev' }}
        run: echo "🔍 Special steps for selected environment ${{ inputs.environments }}" >> $GITHUB_STEP_SUMMARY

  production:
    runs-on: ubuntu-latest
    needs: [dev, qa]
    environment: production
    steps:
      - run: echo ${{ vars.SERVICE_ACCOUNT_NAME }} ; echo ${{ secrets.SERVICE_ACCOUNT_PASSWORD }}
      - if: ${{ inputs.environments == 'production' }}
        run: echo "🔍 Special steps for selected environment ${{ inputs.environments }}" >> $GITHUB_STEP_SUMMARY
