name: My Actions Demo
on: 
  workflow_dispatch:
    inputs:
      env:
        type: environment
        description: Environment to deploy to
    
jobs:
  ShowInfo:   
    environment: ${{ github.events.inputs.env }}
    runs-on: Ubuntu-latest
    steps:
      - run: |
          echo "🎣 ${{github.action_repository}} triggered by ${{ github.event_name}}"
          echo "${{ github.events.inputs.env }} : ${{ vars.service_account_name }} : ${{ vars.service_account_password }}"
          echo " ${{ toJson(vars) }}"
      - name: List files
        run: |
          echo "The repo ${{ github.repository }} contains the following"
          tree
      
    
