name: My Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: [./FancyAction/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 1 * * 0'
  workflow_dispatch:

jobs:
  ShowInfo:   
    strategy:
      matrix:
        env: [dev,test,qa]
    environment: ${{ matrix.env }}
    runs-on: Ubuntu-latest
    steps:
      - run: |
          echo "🎣 ${{github.action_repository}} triggered by ${{ github.event_name}}"
          echo "${{matrix.env}} : ${{ vars.service_account_name }} : ${{ vars.service_account_name }}"
      - name: List files
        run: |
          echo "The repo ${{ github.repository }} contains the following"
          tree
      
    
